export const horses = [
  'Forte',
  'Tapit Trice',
  'Angel of Empire',
  'Derma Sotogake',
  'Kingsbarn',
  "Two Phil's",
  'Mage',
  'Verifying',
  'Confidence Game',
  'Verifying',
  'Hit Show',
  'Kingsbarns',
  'Reincarnate',
  'Disarm',
  "Jace's Road",
  'Sun Thunder',
  'Raise Cain',
  'Rocket Can',
  'Cyclone Mischief',
  'Mandarin Hero',
  'King Russell',
];
